///////////////////////////////////////////////////////////
//  ShopPOIInfo.cs
//  Implementation of the Class ShopPOIInfo
//  Generated by Enterprise Architect
//  Created on:      29-8ÔÂ-2016 9:52:02
//  Original author: Jango
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Jango.Lab.Models {
	/// <summary>
	/// ÃÅµê
	/// </summary>
	public class ShopPOIInfo {

	

	}//end ShopPOIInfo

}//end namespace Jango.Lab.Models