///////////////////////////////////////////////////////////
//  EnumMessageType.cs
//  Implementation of the Enumeration EnumMessageType
//  Generated by Enterprise Architect
//  Created on:      29-8ÔÂ-2016 9:52:02
//  Original author: Jango
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Jango.Lab.Models {
	public enum EnumMessageType  {

		Template,
		SMS

	}//end EnumMessageType

}//end namespace Jango.Lab.Models