///////////////////////////////////////////////////////////
//  EnumPayStatus.cs
//  Implementation of the Enumeration EnumPayStatus
//  Generated by Enterprise Architect
//  Created on:      29-8ÔÂ-2016 9:52:02
//  Original author: Jango
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Jango.Lab.Models {
	public enum EnumPayStatus  {

		ToPay,
		Paying,
		Paid

	}//end EnumPayStatus

}//end namespace Jango.Lab.Models