///////////////////////////////////////////////////////////
//  EnumOrderStatus.cs
//  Implementation of the Enumeration EnumOrderStatus
//  Generated by Enterprise Architect
//  Created on:      29-8ÔÂ-2016 9:52:02
//  Original author: Jango
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Jango.Lab.Models {
	public enum EnumOrderStatus  {

		Faild,
		Success,
		AuditFaild,
		Finished

	}//end EnumOrderStatus

}//end namespace Jango.Lab.Models