///////////////////////////////////////////////////////////
//  EnumCoachStatus.cs
//  Implementation of the Enumeration EnumCoachStatus
//  Generated by Enterprise Architect
//  Created on:      29-8ÔÂ-2016 9:52:01
//  Original author: Jango
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Jango.Lab.Models {
	public enum EnumCoachStatus  {

		On,
		Off

	}//end EnumCoachStatus

}//end namespace Jango.Lab.Models