///////////////////////////////////////////////////////////
//  EnumLoglevel.cs
//  Implementation of the Enumeration EnumLoglevel
//  Generated by Enterprise Architect
//  Created on:      29-8ÔÂ-2016 9:52:02
//  Original author: Jango
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Jango.Lab.Models {
	public enum EnumLoglevel  {

		Error,
		Trace,
		Info

	}//end EnumLoglevel

}//end namespace Jango.Lab.Models